# Generated by Django 5.0 on 2024-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drinks', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Qty', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Discription', models.TextField()),
            ],
        ),
    ]
