# Generated by Django 5.0 on 2024-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Drink', models.CharField(max_length=50)),
                ('Des', models.TextField()),
                ('Quantity', models.CharField(max_length=10)),
                ('Picture', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
