# Generated by Django 5.0 on 2024-02-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=50)),
                ('L_Name', models.CharField(max_length=50)),
                ('E_Mail', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='price',
        ),
    ]
